#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


def clamp(v, lo=0.0, hi=1.0):
    return max(lo, min(hi, float(v)))


def faust_from_tone(tone: dict) -> str:
    name = tone.get("name", "Xiwu Tone")
    osc = tone["osc"]
    env = tone["env"]
    character = tone["character"]
    eq4 = tone["eq4"]

    s_sine = clamp(osc.get("sine", 0.0))
    s_saw = clamp(osc.get("saw", 0.0))
    s_square = clamp(osc.get("square", 0.0))
    s_tri = clamp(osc.get("triangle", 0.0))
    s_noise = clamp(osc.get("noise", 0.0))
    s_sub = clamp(osc.get("sub_octave", 0.0))

    atk = max(0.001, float(env.get("attack", 0.01)))
    dec = max(0.001, float(env.get("decay", 0.2)))
    sus = clamp(env.get("sustain", 0.6))
    rel = max(0.001, float(env.get("release", 0.3)))

    drive = clamp(character.get("drive", 0.2))
    bright = clamp(character.get("brightness", 0.5))

    low = clamp(eq4.get("low", 0.5))
    low_mid = clamp(eq4.get("low_mid", 0.5))
    high_mid = clamp(eq4.get("high_mid", 0.5))
    high = clamp(eq4.get("high", 0.5))

    return f'''// Auto-generated by tone_json_to_faust.py
// Tone: {name}
import("stdfaust.lib");

freq = hslider("freq[unit:Hz]", 110, 20, 2000, 0.01);
gate = button("gate");
vel = hslider("vel", 0.8, 0, 1, 0.01);

mix_sine = {s_sine:.6f};
mix_saw = {s_saw:.6f};
mix_square = {s_square:.6f};
mix_tri = {s_tri:.6f};
mix_noise = {s_noise:.6f};
mix_sub = {s_sub:.6f};

a = {atk:.6f};
d = {dec:.6f};
s = {sus:.6f};
r = {rel:.6f};

drive = {drive:.6f};
brightness = {bright:.6f};

low = {low:.6f};
low_mid = {low_mid:.6f};
high_mid = {high_mid:.6f};
high = {high:.6f};

env = en.adsre(a, d, s, r, gate);

lowGain = 0.45 + low * 1.20;
lowMidGain = 0.45 + low_mid * 1.10;
highMidGain = 0.45 + high_mid * 1.10;
highGain = 0.45 + high * 1.20;

sat(x) = x / (1 + abs(x) * (0.8 + drive * 4));

proc = (
    (mix_sine * os.osc(freq) * lowGain)
  + (mix_sub * os.square(freq * 0.5) * lowGain)
  + (mix_saw * os.sawtooth(freq) * lowMidGain)
  + (mix_square * os.square(freq) * lowMidGain)
  + (mix_tri * os.triangle(freq) * highMidGain)
  + (mix_noise * no.noise * highGain * 0.25)
) * vel * env : sat : *(0.62 + brightness * 0.50);

process = proc, proc;
'''


def main() -> int:
    parser = argparse.ArgumentParser(description="Convert Xiwu ToneSpec JSON to Faust DSP")
    parser.add_argument("--in", dest="input", required=True, help="input tone json")
    parser.add_argument("--out", dest="output", required=True, help="output .dsp path")
    args = parser.parse_args()

    src = Path(args.input)
    dst = Path(args.output)
    tone = json.loads(src.read_text(encoding="utf-8-sig"))

    if tone.get("spec_version") != "tone_spec_v1":
        raise ValueError("Unsupported spec_version")

    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(faust_from_tone(tone), encoding="utf-8")
    print(f"generated {dst}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
